on:
  issues:
    types: [labeled]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Videndum/release-mastermind@0.0.0-alpha+1565

        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
